(define (domain blocksworld)
  (:requirements :strips)
(:predicates (clear ?x)
             (on-table ?x)
             (arm-empty)
             (holding ?x)
             (on ?x ?y)
	     (ftrue))
 
(:action pickup
  :parameters (?ob)
  :precondition (and (clear ?ob) (on-table ?ob) (arm-empty))
  :effect (and (holding ?ob) (not (clear ?ob)) (not (on-table ?ob)) 
               (not (arm-empty))))

(:action putdown
  :parameters  (?ob)
  :precondition (and (holding ?ob))
  :effect (and (clear ?ob) (arm-empty) (on-table ?ob) 
               (not (holding ?ob))))

(:action stack
  :parameters  (?ob ?underob)
  :precondition (and (clear ?underob) (holding ?ob))
  :effect (and (arm-empty) (clear ?ob) (on ?ob ?underob)
               (not (clear ?underob)) (not (holding ?ob))))

(:action unstack
  :parameters  (?ob ?underob)
  :precondition (and (on ?ob ?underob) (clear ?ob) (arm-empty))
  :effect (and (holding ?ob) (clear ?underob)
               (not (on ?ob ?underob)) (not (clear ?ob)) (not (arm-empty))))

)
(define
(planprog Degree10-110-PFILE70)
(:domain blocksworld)
(:objects b1 b2 )
(:init
(arm-empty)
(on b1 b2)
(on-table b2)
(clear b1)
(ftrue)
)
(:init-app n0)
(:transitions
(n0 n1 (:goal (on b2 b1)) )
(n1 n2 (:goal (holding b1)) )
(n2 n3 (:goal (and (clear b1) (clear b2))) )
(n3 n4 (:goal (and (on-table b1) (on-table b2))) )
(n4 n5 (:goal (and (on-table b1) (on-table b2))) )
(n5 n6 (:goal (clear b1)) )
(n6 n7 (:goal (arm-empty)) )
(n7 n8 (:goal (on-table b1)) )
(n8 n9 (:goal (on b2 b1)) )
(n9 n10 (:goal (on-table b2)) )
(n10 n5 (:goal (arm-empty)) )
(n8 n7 (:goal (on-table b1)) )
(n8 n3 (:goal (and (on-table b1) (on-table b2))) )
(n10 n4 (:goal (clear b1)) )
(n9 n0 (:goal (clear b1)) )
(n9 n6 (:goal (on-table b1)) )
(n9 n5 (:goal (on-table b2)) )
(n2 n8 (:goal (arm-empty)) )
(n5 n4 (:goal (and (clear b1) (clear b2))) )
(n8 n4 (:goal (clear b2)) )
(n0 n4 (:goal (and (clear b1) (clear b2))) )
(n1 n6 (:goal (on b1 b2)) )
(n10 n8 (:goal (on-table b2)) )
(n5 n3 (:goal (clear b2)) )
(n10 n0 (:goal (holding b2)) )
(n2 n1 (:goal (holding b1)) )
(n10 n6 (:goal (clear b1)) )
(n3 n9 (:goal (and (clear b1) (clear b2))) )
(n9 n4 (:goal (and (on-table b1) (on-table b2))) )
(n8 n1 (:goal (on b2 b1)) )
(n3 n1 (:goal (and (clear b1) (clear b2))) )
(n3 n10 (:goal (and (clear b1) (clear b2))) )
(n6 n9 (:goal (clear b2)) )
(n6 n4 (:goal (and (on-table b1) (on-table b2))) )
(n4 n9 (:goal (arm-empty)) )
(n9 n3 (:goal (holding b2)) )
(n8 n6 (:goal (holding b2)) )
(n4 n10 (:goal (holding b2)) )
(n7 n5 (:goal (holding b2)) )
(n0 n3 (:goal (holding b1)) )
(n4 n7 (:goal (on b1 b2)) )
(n5 n0 (:goal (on-table b1)) )
(n7 n1 (:goal (holding b2)) )
(n1 n10 (:goal (on-table b1)) )
(n5 n1 (:goal (clear b1)) )
(n0 n6 (:goal (and (clear b1) (clear b2))) )
(n1 n3 (:goal (on-table b1)) )
(n4 n6 (:goal (holding b1)) )
(n0 n2 (:goal (clear b1)) )
(n2 n0 (:goal (and (clear b1) (clear b2))) )
(n4 n0 (:goal (and (clear b1) (clear b2))) )
(n9 n7 (:goal (clear b2)) )
(n2 n5 (:goal (on-table b1)) )
(n3 n6 (:goal (and (on-table b1) (on-table b2))) )
(n7 n2 (:goal (on-table b1)) )
(n8 n0 (:goal (holding b2)) )
(n1 n4 (:goal (on b2 b1)) )
(n10 n1 (:goal (clear b1)) )
(n3 n2 (:goal (on b2 b1)) )
(n0 n7 (:goal (on-table b2)) )
(n6 n3 (:goal (arm-empty)) )
(n2 n7 (:goal (on-table b2)) )
(n7 n10 (:goal (and (on-table b1) (on-table b2))) )
(n5 n7 (:goal (on b2 b1)) )
(n8 n10 (:goal (arm-empty)) )
(n3 n5 (:goal (holding b1)) )
(n1 n8 (:goal (clear b2)) )
(n10 n9 (:goal (on-table b1)) )
(n8 n5 (:goal (and (on-table b1) (on-table b2))) )
(n10 n3 (:goal (and (on-table b1) (on-table b2)) )) )
)
