(define (domain blocksworld)
  (:requirements :strips)
(:predicates (clear ?x)
             (on-table ?x)
             (arm-empty)
             (holding ?x)
             (on ?x ?y)
	     (ftrue))
 
(:action pickup
  :parameters (?ob)
  :precondition (and (clear ?ob) (on-table ?ob) (arm-empty))
  :effect (and (holding ?ob) (not (clear ?ob)) (not (on-table ?ob)) 
               (not (arm-empty))))

(:action putdown
  :parameters  (?ob)
  :precondition (and (holding ?ob))
  :effect (and (clear ?ob) (arm-empty) (on-table ?ob) 
               (not (holding ?ob))))

(:action stack
  :parameters  (?ob ?underob)
  :precondition (and (clear ?underob) (holding ?ob))
  :effect (and (arm-empty) (clear ?ob) (on ?ob ?underob)
               (not (clear ?underob)) (not (holding ?ob))))

(:action unstack
  :parameters  (?ob ?underob)
  :precondition (and (on ?ob ?underob) (clear ?ob) (arm-empty))
  :effect (and (holding ?ob) (clear ?underob)
               (not (on ?ob ?underob)) (not (clear ?ob)) (not (arm-empty))))

)
(define
(planprog Degree10-110-PFILE70)
(:domain blocksworld)
(:objects b1 b2 )
(:init
(arm-empty)
(on b1 b2)
(on-table b2)
(clear b1)
(ftrue)
)
(:initnode n0)
(:transitions
(n0 n1 (on b2 b1) )
(n1 n2 (holding b1) )
(n2 n3 (and (clear b1) (clear b2)) )
(n3 n4 (and (on-table b1) (on-table b2)) )
(n4 n5 (and (on-table b1) (on-table b2)) )
(n5 n6 (clear b1) )
(n6 n7 (arm-empty) )
(n7 n8 (on-table b1) )
(n8 n9 (on b2 b1) )
(n9 n10 (on-table b2) )
(n10 n5 (arm-empty) )
(n8 n7 (on-table b1) )
(n8 n3 (and (on-table b1) (on-table b2)) )
(n10 n4 (clear b1) )
(n9 n0 (clear b1) )
(n9 n6 (on-table b1) )
(n9 n5 (on-table b2) )
(n2 n8 (arm-empty) )
(n5 n4 (and (clear b1) (clear b2)) )
(n8 n4 (clear b2) )
(n0 n4 (and (clear b1) (clear b2)) )
(n1 n6 (on b1 b2) )
(n10 n8 (on-table b2) )
(n5 n3 (clear b2) )
(n10 n0 (holding b2) )
(n2 n1 (holding b1) )
(n10 n6 (clear b1) )
(n3 n9 (and (clear b1) (clear b2)) )
(n9 n4 (and (on-table b1) (on-table b2)) )
(n8 n1 (on b2 b1) )
(n3 n1 (and (clear b1) (clear b2)) )
(n3 n10 (and (clear b1) (clear b2)) )
(n6 n9 (clear b2) )
(n6 n4 (and (on-table b1) (on-table b2)) )
(n4 n9 (arm-empty) )
(n9 n3 (holding b2) )
(n8 n6 (holding b2) )
(n4 n10 (holding b2) )
(n7 n5 (holding b2) )
(n0 n3 (holding b1) )
(n4 n7 (on b1 b2) )
(n5 n0 (on-table b1) )
(n7 n1 (holding b2) )
(n1 n10 (on-table b1) )
(n5 n1 (clear b1) )
(n0 n6 (and (clear b1) (clear b2)) )
(n1 n3 (on-table b1) )
(n4 n6 (holding b1) )
(n0 n2 (clear b1) )
(n2 n0 (and (clear b1) (clear b2)) )
(n4 n0 (and (clear b1) (clear b2)) )
(n9 n7 (clear b2) )
(n2 n5 (on-table b1) )
(n3 n6 (and (on-table b1) (on-table b2)) )
(n7 n2 (on-table b1) )
(n8 n0 (holding b2) )
(n1 n4 (on b2 b1) )
(n10 n1 (clear b1) )
(n3 n2 (on b2 b1) )
(n0 n7 (on-table b2) )
(n6 n3 (arm-empty) )
(n2 n7 (on-table b2) )
(n7 n10 (and (on-table b1) (on-table b2)) )
(n5 n7 (on b2 b1) )
(n8 n10 (arm-empty) )
(n3 n5 (holding b1) )
(n1 n8 (clear b2) )
(n10 n9 (on-table b1) )
(n8 n5 (and (on-table b1) (on-table b2)) )
(n10 n3 (and (on-table b1) (on-table b2)) )
)
)
